### ISSUE TITLE
Map Colors

### ISSUE THREAD

**Issue by ReikiMan** [DualBrain/VbRogue#6]
The current prototype does not use the correct colors.

**Comment by DualBrain** [comment]
By correct colors, do you mean the original MS-DOS (CGA/EGA/VGA) colors?

**Comment by ReikiMan** [comment]
Yes.

**Comment by DualBrain** [comment]
Yes, I noticed the same thing.  It appears that the "dark yellow" isn't "orangish-brownish".  I'll see if I can find a solution.

**Comment by DualBrain** [comment]
This issue should now be resolved.
